require('dotenv').config();
const mongoose = require('mongoose');
const Job = require('./models/Job');

const jobs = [
  {
    title: 'Frontend Developer',
    company: 'CodeGen International',
    location: 'colombo',
    level: 'entry',
    modality: 'hybrid',
    salary: 120000,
    description: 'Build responsive user interfaces using React.js and modern CSS frameworks. Collaborate with UX designers to implement pixel-perfect designs and optimize web application performance.',
    contactEmail: 'careers@codegen.lk',
  },
  {
    title: 'Backend Developer',
    company: 'Virtusa',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'on-site',
    salary: 250000,
    description: 'Design and develop scalable RESTful APIs using Node.js and Express. Work with MongoDB and PostgreSQL databases to build robust backend systems for enterprise clients.',
    contactEmail: 'jobs@virtusa.com',
  },
  {
    title: 'Full Stack Developer',
    company: 'Sysco LABS',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'hybrid',
    salary: 300000,
    description: 'Develop end-to-end web applications using the MERN stack. Participate in agile sprints, code reviews, and contribute to architectural decisions for cloud-native applications.',
    contactEmail: 'talent@syscolabs.com',
  },
  {
    title: 'Software Engineering Intern',
    company: 'WSO2',
    location: 'colombo',
    level: 'internship',
    modality: 'on-site',
    salary: 50000,
    description: 'Join our engineering team to gain hands-on experience in open-source software development. Work on identity and access management products using Java and React technologies.',
    contactEmail: 'internships@wso2.com',
  },
  {
    title: 'DevOps Engineer',
    company: 'IFS',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'hybrid',
    salary: 350000,
    description: 'Manage CI/CD pipelines, containerized deployments using Docker and Kubernetes. Automate infrastructure provisioning with Terraform and monitor system health using Prometheus and Grafana.',
    contactEmail: 'devops@ifs.com',
  },
  {
    title: 'QA Automation Engineer',
    company: '99X Technology',
    location: 'colombo',
    level: 'entry',
    modality: 'on-site',
    salary: 130000,
    description: 'Write and maintain automated test suites using Selenium and Cypress. Perform regression testing, API testing, and collaborate with developers to ensure software quality standards.',
    contactEmail: 'qa@99x.io',
  },
  {
    title: 'Mobile App Developer',
    company: 'Rootcode Labs',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'remote',
    salary: 280000,
    description: 'Develop cross-platform mobile applications using React Native and Flutter. Integrate REST APIs, push notifications, and implement offline-first architectures for mobile apps.',
    contactEmail: 'mobile@rootcodelabs.com',
  },
  {
    title: 'Data Engineer',
    company: 'Calcey Technologies',
    location: 'colombo',
    level: 'senior',
    modality: 'hybrid',
    salary: 400000,
    description: 'Design and build data pipelines using Apache Spark and Airflow. Create ETL processes, manage data warehouses, and work with big data technologies to support analytics teams.',
    contactEmail: 'data@calcey.com',
  },
  {
    title: 'UI/UX Designer',
    company: 'Elegant Media',
    location: 'kandy',
    level: 'entry',
    modality: 'on-site',
    salary: 100000,
    description: 'Create wireframes, prototypes, and high-fidelity mockups using Figma and Adobe XD. Conduct user research, usability testing, and design intuitive interfaces for web and mobile apps.',
    contactEmail: 'design@elegantmedia.com',
  },
  {
    title: 'Cloud Solutions Architect',
    company: 'Pearson Lanka',
    location: 'colombo',
    level: 'senior',
    modality: 'hybrid',
    salary: 500000,
    description: 'Architect cloud-native solutions on AWS and Azure. Lead migration projects, design microservices architectures, and mentor engineering teams on cloud best practices and security.',
    contactEmail: 'cloud@pearson.lk',
  },
  {
    title: 'Machine Learning Engineer',
    company: 'Zone24x7',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'on-site',
    salary: 350000,
    description: 'Develop and deploy machine learning models for recommendation systems and computer vision. Work with TensorFlow, PyTorch, and implement MLOps pipelines for production environments.',
    contactEmail: 'ml@zone24x7.com',
  },
  {
    title: 'Cybersecurity Analyst',
    company: 'Sri Lanka CERT',
    location: 'colombo',
    level: 'entry',
    modality: 'on-site',
    salary: 150000,
    description: 'Monitor and respond to security incidents, conduct vulnerability assessments, and implement security measures. Analyze threat intelligence and prepare security audit reports.',
    contactEmail: 'security@slcert.gov.lk',
  },
  {
    title: 'React Native Developer',
    company: 'Arimac',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'hybrid',
    salary: 270000,
    description: 'Build high-performance mobile applications using React Native. Implement complex animations, integrate native modules, and optimize app performance for iOS and Android platforms.',
    contactEmail: 'careers@arimac.digital',
  },
  {
    title: 'Python Developer',
    company: 'Intellect Design Arena',
    location: 'remote',
    level: 'entry',
    modality: 'remote',
    salary: 160000,
    description: 'Develop backend services and automation scripts using Python and Django. Work on fintech solutions, integrate payment gateways, and write clean, testable, and maintainable code.',
    contactEmail: 'python@intellectdesign.com',
  },
  {
    title: 'Database Administrator',
    company: 'Dialog Axiata',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'on-site',
    salary: 280000,
    description: 'Manage and optimize MySQL, PostgreSQL, and MongoDB databases. Perform backup and recovery operations, query optimization, and ensure database security and high availability.',
    contactEmail: 'dba@dialog.lk',
  },
  {
    title: 'Technical Lead',
    company: 'Wavenet International',
    location: 'colombo',
    level: 'senior',
    modality: 'hybrid',
    salary: 450000,
    description: 'Lead a team of 8 developers building SaaS products. Drive technical architecture decisions, conduct code reviews, mentor junior developers, and ensure delivery of high-quality software.',
    contactEmail: 'lead@wavenet.lk',
  },
  {
    title: 'WordPress Developer',
    company: 'Developer Starter',
    location: 'kandy',
    level: 'entry',
    modality: 'remote',
    salary: 80000,
    description: 'Build custom WordPress themes and plugins for client websites. Implement responsive designs, optimize page speed, and manage hosting and deployment of WordPress sites.',
    contactEmail: 'wp@developerstarter.com',
  },
  {
    title: 'Systems Engineer',
    company: 'Millennium IT ESP',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'on-site',
    salary: 300000,
    description: 'Design and maintain IT infrastructure including servers, networks, and storage systems. Implement monitoring solutions, manage Linux/Windows environments, and ensure 99.9% uptime.',
    contactEmail: 'syseng@millenniumitesp.com',
  },
  {
    title: 'Angular Developer',
    company: 'Embla Software',
    location: 'galle',
    level: 'entry',
    modality: 'hybrid',
    salary: 110000,
    description: 'Develop enterprise web applications using Angular and TypeScript. Implement state management with NgRx, write unit tests, and integrate RESTful APIs for business applications.',
    contactEmail: 'angular@emblasoftware.com',
  },
  {
    title: 'Site Reliability Engineer',
    company: 'Axiata Digital Labs',
    location: 'colombo',
    level: 'senior',
    modality: 'hybrid',
    salary: 420000,
    description: 'Ensure reliability and scalability of distributed systems. Build observability platforms, manage incident response, and automate toil using Go and Python scripting.',
    contactEmail: 'sre@axiatadigitallabs.com',
  },
  {
    title: 'Java Developer',
    company: 'Virtusa',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'on-site',
    salary: 260000,
    description: 'Develop enterprise Java applications using Spring Boot and Hibernate. Build microservices, implement message queues with Kafka, and deploy applications on cloud infrastructure.',
    contactEmail: 'java@virtusa.com',
  },
  {
    title: 'IT Support Engineer',
    company: 'SLIIT Campus',
    location: 'kandy',
    level: 'entry',
    modality: 'on-site',
    salary: 75000,
    description: 'Provide technical support to faculty, staff, and students. Troubleshoot hardware and software issues, manage network configurations, and maintain IT lab equipment and systems.',
    contactEmail: 'it-support@sliit.lk',
  },
  {
    title: 'Blockchain Developer',
    company: 'TradeFinex',
    location: 'remote',
    level: 'senior',
    modality: 'remote',
    salary: 550000,
    description: 'Develop smart contracts using Solidity and deploy on Ethereum and Polygon networks. Build decentralized applications with Web3.js and implement token standards and DeFi protocols.',
    contactEmail: 'blockchain@tradefinex.org',
  },
  {
    title: 'API Integration Specialist',
    company: 'Creative Software',
    location: 'colombo',
    level: 'mid-senior',
    modality: 'hybrid',
    salary: 230000,
    description: 'Design and implement third-party API integrations for enterprise clients. Work with REST, GraphQL, and webhook architectures. Document API specifications using OpenAPI/Swagger.',
    contactEmail: 'api@creativesoftware.com',
  },
  {
    title: 'Game Developer Intern',
    company: 'Bhasha Lanka',
    location: 'galle',
    level: 'internship',
    modality: 'on-site',
    salary: 45000,
    description: 'Assist in developing educational games using Unity 3D and C#. Create 2D/3D game assets, implement game mechanics, and test gameplay on multiple platforms including web and mobile.',
    contactEmail: 'games@bhashalanka.com',
  },
];

async function seed() {
  try {
    await mongoose.connect(
      process.env.MONGO_URI || 'mongodb://localhost:27017/unihelp'
    );
    console.log('Connected to MongoDB');

    await Job.deleteMany({});
    console.log('Cleared existing jobs');

    const inserted = await Job.insertMany(jobs);
    console.log(`✅ Successfully inserted ${inserted.length} jobs`);

    await mongoose.disconnect();
    console.log('Disconnected from MongoDB');
  } catch (error) {
    console.error('Seed error:', error.message);
    process.exit(1);
  }
}

seed();
